sudo: required

language: java

jdk:
  - openjdk11

services:
  - docker
  
branches:
  only:
    - master

install: true
  
script:
  - ./gradlew testImage
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push sogis/indexupdater:latest
  - docker push sogis/indexupdater:$TRAVIS_BUILD_NUMBER
