@startuml
[Searchservice] as ss
() HTTP as ssi
ssi - ss

[GRETL - JOB] as gretl

[Indexupdater] as iu
() HTTP as iui
iui - iu

package "Solr" {
  [DIH - Data Import Handler] as dih
  () HTTP as dihi

  () HTTP as uhi
  () HTTP as qi

  uhi - [Update]
  dihi - [dih]
  qi - [Query]
}

[Permission Service] as ps
() HTTP as psi
psi - ps
 
database "PostgreSQL" {
  [View *_solr_v] as view
}

[Search Client] --> ssi

[AGDI] --> iui
gretl --> iui

ss --> qi
ss --> psi

iu --> uhi
iu --> dihi
iu --> qi

dih --> view : jdbc

legend bottom left
  Komponenten-Diagramm der SOLR-Suche:

  Beinhaltet die für die Bereitstellung des Suchservice notwendigen Komponenten.
  Die Clients konsumieren mittels Suchanfragen den Searchservice.
  Die Aktualisierung des Suchindexes erfolgt über den Indexupdater.
  
  Abstraktionen im Diagramm:
  - Stellvertretend ist nur eine Datenbank als Datenquelle für den SOLR-Index dargestellt.
  - Die Abhängkeiten des Permission Service sind nicht abgebildet.
endlegend
@enduml